name: CI for cloud7-dataapi-spring

on: 
 push:
  branches: 
    - master
    - feature/**

jobs:
  build:
   runs-on: ubuntu-latest
   
   permissions:
     id-token: write
     contents: read
     
   env:
    APP_NAME: ${{ github.event.repository.name }}  # Repo name as app name
    BUILD_NO: ${{ github.run_number }} 
    
   steps:
   # Checkout source code
    - name: Checkout source code
      uses: actions/checkout@v4 

   # Set up java environment
   #  - name: Set up JDK
   #    uses: actions/setup-java@v4
   #    with:
   #      java-version: '21'
   #      distribution: 'oracle'
        
   # # Build jar using Maven
   #  - name: Build using Maven
   #    run: mvn clean install

   # # Build and tag docker image
   #  - name: Build Docker image
   #    run: |
   #     echo "Building docker image for $APP_NAME"
   #     docker build -t $APP_NAME -f docker/Dockerfile .

    - name: Assume Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::174627743630:role/GithubActionsImagePushRole
          role-session-name: GitHubActionsSession
          aws-region: us-east-1
